name: alphawallet
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  amplify_auth_cognito: ^2.11.0
  amplify_auth_cognito_dart: ^2.11.0
  amplify_flutter: ^2.11.0
  equatable: ^2.0.5
  http: ^1.2.2
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  collection: ^1.18.0
  fl_chart: ^0.69.0
  uuid: ^4.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - amplifyconfiguration.json
